### ISSUE TITLE
Calendar Object Deleted

### ISSUE THREAD

**Issue by swelcom** [kffl/nextcloud-webhooks#13]
Hi there

Creating and updating works perfectly with Zapier, but if I delete a calendar entry, the change does not arrive at Zapier. Would it also be possible to trigger an event when a calendar item is deleted?

Greetings

**Comment by kffl** [comment]
Hi @swelcom 

Thanks for reporting this feature request. It seems that it could be implemented by adding listeners for `CalendarObjectDeletedEvent` as well as `CalendarObjectMovedToTrashEvent`. The latter was added in v22 and seems to be triggered when a soft-delete of a calendar event is performed. Since stable releases of v22 have been around for over a year, it seems reasonable to include both events and bump the required Nextcloud version of this app to 22.

If everything goes according to plan, I might find some time to implement this during the weekend. If someone else would like to contribute, please let me know in this thread. For now, I'm marking this as a good first issue, since it should be fairly straightforward to implement.
