### ISSUE TITLE
Nextcloud 24?

### ISSUE THREAD

**Issue by Elliot-Construct** [kffl/nextcloud-webhooks#6]
When do you propose Nextcloud 24 compatibility will be available?

**Comment by kffl** [comment]
I still have some manual testing to perform with Nextcloud 24 and PHP 8.1. Since the critical changes documented in v24 don't seem to be affecting the APIs used by this app, it its very likely that no changes to the app's codebase will be required. If that turns out to be the case, the next version should be released on Friday.

In order to automate the process of app testing for future Nextcloud releases, so as to be able to ship updates faster, I intend to setup a testing pipeline with a Node.js server receiving webhook notifications regarding events triggered from the frontend via Cypress (described in #7 ).
